# Project information
sonar.projectKey=abdelh17_Quolance
sonar.organization=abdelh17

# Source code location
sonar.sources=src
sonar.tests=src

# Test patterns
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,src/serviceWorker.ts

# Exclude directories
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**

# Test Coverage Report
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Language
sonar.language=js
sonar.sourceEncoding=UTF-8